stages:
  #- code_quality
  #- test
  - deploy


code_quality:
  stage: code_quality
  image: python:3.10
  script:
    - pip install ruff
    - ruff --version
    - ruff .

pytest:
  stage: test
  image: python:3.1
  variables:
    PYTHONDONTWRITEBYTECODE: 1
    PYTHONPATH: ${PYTHONPATH}:${CI_PROJECT_DIR}
    SECURE_FILES_DOWNLOAD_PATH: './tests/data_test/'

  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - pip install -r requirements.txt  # Install your project dependencies
    - pytest -m "not skip_this"

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

deployment:
  stage: deploy
  image: docker:24.0.5

  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
  variables:
    DOCKER_HOST: tcp://docker:2375

  script:
    - apk add --no-cache --update python3 py3-pip
    - apk add --no-cache --update --virtual=build gcc musl-dev python3-dev libffi-dev openssl-dev cargo make
    - pip3 install --no-cache-dir --prefer-binary azure-cli
    - apk del build
    - az acr login --name ${AZURE_CONTAINER_REGISTRY_NAME} -u ${AZURE_USERNAME} -p ${AZURE_PASSWORD}
    - docker build -t ${AZURE_DOCKER_IMAGE_NAME} .
    - docker push ${AZURE_DOCKER_IMAGE_NAME}

#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
