# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "./tests", #ignore tests modules
    "_profiling.py"
]

target-version = "py310"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.S
# All rules are listed here : https://docs.astral.sh/ruff/rules/#pyflakes-f
select = ["F", "E", "W", "I", "N", "UP", "YTT", "ANN", "ASYNC", "BLE", "FBT", "B", "A", "COM", "C4", "T10",
        "DJ", "EM", "EXE", "FA", "ISC", "ICN", "G", "INP", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET",
        "SLF", "SLOT", "SIM", "TID", "TCH", "INT", "TD", "ERA", "S", "B905", "B008", "DTZ", "SIM105", "A003",
        "PTH"]
ignore = [
    # TO IGNORE:
    "FBT", # This limits the use of default boolean arguments in function definitions
    "C", # McCabe complexity ignored
    "S101", #Use of `assert` detected
    "ANN101", #Missing type annotation for `self` in method
    "ANN102", #Missing type annotation for `cls` in classmethod
    "ANN002", #Missing type annotation for *arg
    "ANN003", #Missing type annotation for **kwarg
    "UP007", #Use `X | Y` for type annotations: issues with the Optional module of type package
    "RET504", # prevents assignment of a variable before its return. Annoying for understandable code
    "RET505", # forces if else logic. Annoying for understandable code
    "RET507", #same as RET505
    "ARG", # prevents assignmenet of unused variables. This however is usefull for later use of the variable
    "FIX", # force issue resolving (in todos)
    "TD003", #force issue link in todos
    "COM812",
    "ISC001",
    "SIM118", # this prevents the use of keys() in dictionaries. But it forgets pd.Series have keys()...
    "SIM108",
    "UP032"

]


# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[lint.pycodestyle]
max-line-length = 100

# define immutables like fastapi.Depends
[flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends",
    "fastapi.File", "fastapi.params.File",
    "fastapi.Query", "fastapi.params.Query"]

# ignore built in python keywords
[flake8-builtins]
builtins-ignorelist = ["id", "type"]
